baseURL: /
languageCode: en-us
title: Nhuyhoa Recipes
theme: vanilla-bootstrap-hugo-theme
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$", "\\.db$", "\\.R$"]

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

# See https://feathericons.com/
# The value of pre is the icon name
menu:
  nav:
  - name: Home
    pre: home
    url: /
    weight: 1
  - name: Recipes
    pre: thumbs-up
    url: /post/
    weight: 2
  - name: Categories
    pre: tag
    url: /tags/
    weight: 3

params:
  includeBootstrapJs: false
  showActiveNav: true
  containerMaxWidth: 700px
  dateFormat: 2006-Jan-02
  homeText: Welcome to the Vanilla theme demo. Have a look around. Maybe even eat some ice cream.
  footerText: Made with [Hugo](https://gohugo.io/) & [Vanilla](https://github.com/zwbetz-gh/vanilla-bootstrap-hugo-theme)
  hideFooter: false
  katex: true

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: true
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
