---
title: "Broth"
tags: ['Other', 'Soup']
---

```{r, echo = FALSE, warning = FALSE}
library(tidyverse)
library(knitr)
source('../../../data/util.R')

recipe_name <- 'Broth'
ingredients_query <- glue::glue("SELECT * FROM ingredients WHERE recipe = '{recipe_name}'")
instructions_query <- glue::glue("SELECT * FROM instructions WHERE recipe = '{recipe_name}'")
ingredients <- query_db(ingredients_query, 'md:recipes')
instructions <- query_db(instructions_query, 'md:recipes')

display_ingredients <- ingredients %>%
  dplyr::mutate(idx = ifelse(ingredients == 'any', 1, 0)) %>%
  dplyr::arrange(idx, ingredients) %>%
  dplyr::group_by(recipe, i_type) %>%
  dplyr::mutate(n = row_number()) %>%
  dplyr::ungroup() %>%
  dplyr::select(-idx) %>%
  tidyr::spread(i_type, ingredients)
add_cols <- purrr::discard(c('other', 'meat', 'veggie', 'fruit'), ~ .x %in% colnames(display_ingredients))
for(c in add_cols) display_ingredients[,c] <- NA
display_ingredients <- display_ingredients %>%
  dplyr::select(other, meat, veggie, fruit) %>%
  dplyr::mutate_all(~ ifelse(is.na(.x), '', .x)) %>%
  dplyr::rename(Other = other, Meat = meat, Veggie = veggie, Fruit = fruit)

display_instructions <- instructions %>%
  dplyr::arrange(idx) %>%
  dplyr::select(instructions)
```






### Ingredients

```{r, echo = FALSE}
display_ingredients %>% knitr::kable(format = "html", table.attr = "class = \"presenttab\"")
```

<br>

### Instructions

```{r, echo = FALSE}
display_instructions %>% knitr::kable(format = "html", table.attr = "class = \"presenttabnoh\"")
```

